#! /usr/bin/env bash
# Part of check_oxidized
# Copyright (C) 2021, Jan-Philipp Litza <jpl@plutex.de>.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# /omd/sites/BIS/local/share/check_mk/agents/special
set -eu
set -o pipefail

def usage():
    """
    Print Usage
    """
    print("Oxidized Special Agent for Checkmk")
    print("./oxidized.py <HOSTNAME> <PORT>")
    sys.exit(0)

if len(sys.argv) != 3:
    usage()

HOSTNAME = sys.argv[1]
PORT = sys.argv[2]


OXIDIZED_HOST="${1:-http://HOSTNAME:PORT}"
OXIDIZED_HOST="${OXIDIZED_HOST%/}"

JQ_TEMPLATE='.[] | "<<<<" + .name + ">>>>\n<<<oxidized:sep(124)>>>\n" + ([
  .status,
  .time
] | join("|"))'

if ! curl -s "${OXIDIZED_HOST}/nodes.json" | jq -r "$JQ_TEMPLATE"; then
  echo "Failed to fetch Oxidized devices status" >&2
  exit 1
fi
echo '<<<<>>>>'
