#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#pylint: disable=undefined-variable, missing-docstring
# 2023 created by Carlo Kleinloog
#/omd/sites/BIS/local/share/check_mk/checks
import argparse
import json
import sys
import cmk.utils.password_store

def check_pfsense_arguments(params, hostname, ipaddress):
    args = ''
    args += " " + (params["-H"]) #var1
    args += " " + str(params["port"])#var2
    args += " " + (params["-u"]) #var3
    args += " " + (params["-p"]) #var4
    #args += " " + quote_shell_string(hostname)
    #args += " " + quote_shell_string(ipaddress)
    return args
special_agent_info['pfsense'] = check_pfsense_arguments